title: Ryan Mather
logo: /assets/img/logo2.JPG
description: PhD Candidate in Economics
theme: jekyll-theme-minimal
# can also do "remote_theme: THEME-NAME, replacing THEME-NAME with the name of the theme as shown in the README of the theme's repository."
